# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e41db17b0cef8ea0aba8dcb1f74da7565be52b07981a9d625e2ad20daaf202a882769cafece99976183a43d465460a1af154022486d62b184b00a8c630de6079

test:
  secret_key_base: 755d3c7f604b7d95dc83821f48baff9ca2346e4d727a5b5978699977b098ba304de221d8cb410180bd13f6b692b5fbdf04a5bea6674a4e07a7881e44c43210ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
